### ISSUE TITLE
Error: Connection refused

### ISSUE THREAD

**Issue by rcv11x** [wick3dr0se/irc-bash#1]
I am testing the script and when I run it for the first time I get the following error:
![Screenshot_20231025_172930-bash](https://github.com/wick3dr0se/irc-bash/assets/38696644/4dd66582-8078-403d-99df-3ed2e86c9496)

**Comment by skyler-0** [comment]
I am facing the same issue, maybe I am able to solve it

**Comment by skyler-0** [comment]
![image](https://github.com/wick3dr0se/irc-bash/assets/81177923/878997aa-1309-4a84-a29f-571f87b020e1)
![Screenshot from 2023-10-25 21-48-59](https://github.com/wick3dr0se/irc-bash/assets/81177923/b4b94be1-a3a8-4335-8184-b8e2ae77418a)

I know very basic bash therefore it does not work
but I think that this is a progress

**Comment by Sarvasv-0** [comment]
but hey we have some progress!

**Comment by wick3dr0se** [comment]
Well because you're trying to connect to server on IP 127.0.0.1 with port 6667. These are defaults I set but you can specify an IP as the first argument and port as the second argument. If you don't specify IP than port is first argument. I'll add this to usage. Slipped my mind 😅

Edit: Updated the README with proper usage

**Comment by wick3dr0se** [comment]
@rcv11x @Sarvasv-0 Closing this up!
